---
development:
  pkgmgmt:
    url: 'http://localhost:5100/packages'
  licenses: ''
  users: ''
  kpis: ''
  bss: ''

integration:
#test:
  pkgmgmt:
    url: 'http://localhost:5100/packages'
  licenses: ''
  users: ''
  kpis: ''
  bss: ''

qualification:
  pkgmgmt:
    url: 'http://localhost:5100/packages'
  licenses: ''
  users: ''
  kpis: ''
  bss: ''

demonstration:
#production:
  pkgmgmt:
    url: 'http://localhost:5100/packages'
  licenses: ''
  users: ''
  kpis: ''
  bss: ''
  