---
development:
  pkgmgmt:
    url: 'http://localhost:5100/packages'
  services:
    url: 'http://localhost:5300'
  licenses: ''
  users: ''
  kpis: ''
  bss: ''

test:
  pkgmgmt:
    url: 'http://localhost:5100/packages'
  services:
    url: 'http://localhost:5300'
  licenses: ''
  users: ''
  kpis: ''
  bss: ''

integration:
  pkgmgmt:
    url: 'http://son-gtkpkg:5100/packages'
  services:
    url: 'http://son-gtksrv:5300'
  licenses: ''
  users: ''
  kpis: ''
  bss: ''

qualification:
  pkgmgmt:
    url: 'http://localhost:5100/packages'
  services:
    url: 'http://localhost:5300'
  licenses: ''
  users: ''
  kpis: ''
  bss: ''

demonstration:
#production:
  pkgmgmt:
    url: 'http://localhost:5100/packages'
  services:
    url: 'http://localhost:5300'
  licenses: ''
  users: ''
  kpis: ''
  bss: ''
  