version: '2'
services:
  son-gtkapi:
    image: registry.sonata-nfv.eu:5000/son-gtkapi
    links:
     - son-gtkpkg
     - son-gtksrv
    environment:
     - RACK_ENV=integration
     - PACKAGE_MANAGEMENT_URL=http://son-gtkpkg:5100
     - SERVICE_MANAGEMENT_URL=http://son-gtksrv:5300
    ports:
      - "32001:5000"
    restart: always
    log_driver: "gelf"
    log_opt:
      gelf-address: "udp://logs.sonata-nfv.eu:12900"
      gelf-tag: "int-server-1-gtkapi"

  son-gtkpkg:
    image: registry.sonata-nfv.eu:5000/son-gtkpkg
    environment:
      - RACK_ENV=integration
    ports:
      - "5100"
    restart: always
    log_driver: "gelf"
    log_opt:
      gelf-address: "udp://logs.sonata-nfv.eu:12900"
      gelf-tag: "int-server-1-gtkpkg"

  son-gtksrv:
    image: registry.sonata-nfv.eu:5000/son-gtksrv
    links:
     - broker
     - postgres
    ports:
      - "5300"
    restart: always
    environment:
     - POSTGRES_PASSWORD=sonata
     - POSTGRES_USER=sonatatest
     - RACK_ENV=integration
     - DATABASE_HOST=postgres
     - DATABASE_PORT=5432
     - MQSERVER=amqp://guest:guest@broker:5672
    depends_on:
     - postgres
    extra_hosts:
      - "jenkins.sonata-nfv.eu:192.168.60.5"
    log_driver: "gelf"
    log_opt:
      gelf-address: "udp://logs.sonata-nfv.eu:12900"
      gelf-tag: "int-server-1-gtksrv"

  postgres:
    image: ntboes/postgres-uuid
    ports:
     - "5432"
    environment:
     - POSTGRES_PASSWORD=sonata
     - POSTGRES_USER=sonatatest
     - POSTGRES_DB=gatekeeper
    log_driver: "gelf"
    log_opt:
      gelf-address: "udp://logs.sonata-nfv.eu:12900"
      gelf-tag: "int-server-1-postgres"

  broker:
    image: rabbitmq:3
    ports:
     - "5672"
    log_driver: "gelf"
    log_opt:
      gelf-address: "udp://logs.sonata-nfv.eu:12900"
      gelf-tag: "int-server-1-broker"
