---
- hosts: server
  sudo: yes
  remote_user: ubuntu
  gather_facts: no

  tasks:
    - name: create user
      user:
        name: songtkpr
        createhome: yes
        shell: /bin/bash
        group: root
        generate_ssh_key: yes

    - name: copy my ssh key
      authorized_key:
        key: "{{ lookup('file', '/Users/jbonnet/.ssh/id_rsa.pub') }}"
        user: "songtkpr"
        state: present
#    - name: install required packages
#      apt:
#        name: "{{ item }}"
#        state: present
#        update_cache: yes
#      with_items:
#        - build-essential
#        - git-core
#        - curl
#        - sqlite3
#        - libsqlite3-dev
#        - libxml2-dev
#        - libxslt1-dev
#        - libreadline-dev
#        - libyaml-dev
#        - libcurl4-openssl-dev
#        - libncurses5-dev
#        - libgdbm-dev
#        - libffi-dev
#        - nginx
#        - runit
#        - postgresql-9.3
#        - libpq-dev
#        - nodejs
