---
# tasks file for ruby
- name: NGINX | Updating apt cache
  apt:
    update_cache: yes
                 
- name: NGINX | Installing NGINX
  apt:
    pkg: nginx
    state: latest
                            
- name: NGINX | Starting NGINX
  service:
    name: nginx
    state: started
