---
resources:
  - catalogues
  - repositories
  - gatekeeper

paths:
    catalogues:
        services:
                 GET: read
                 POST: write
                 PUT: write
                 DEL: write
        functions:
                 GET: read
                 POST: write
                 PUT: write
                 DEL: write
        packages:
                 GET: read
                 POST: write
                 PUT: write
                 DEL: write

    repositories:
        requests:
                 GET: read
                 POST: execute
        instances:
                 GET: read
                 POST: write
        vims:
                 GET: read

    gatekeeper:
        /:
