development:
  url: postgresql://localhost/sonata?pool=5
  encoding: unicode

test:
  url: postgresql://localhost/sonata?pool=5
  encoding: unicode
  
integration:
  #url: postgresql://postgres:sonatatest@sp.int.sonata-nfv.eu:5432/gatekeeper?pool=10
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] || 'sp.int.sonata-nfv.eu:5432' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  database: <%= ENV['DATABASE_NAME'] || 'gatekeeper' %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'sonatatest' %>