default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: sonata
#  url: postgresql://localhost/sonata?pool=5

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: 'localhost'
  port: 5432
  database: 'sonata_test'

integration:
  #url: postgresql://postgres:sonatatest@sp.int.sonata-nfv.eu:5432/gatekeeper?pool=10
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] || 'postgres' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  database: <%= ENV['DATABASE_NAME'] || 'gatekeeper' %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'sonatatest' %>
